//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteServico.ServiceReference55 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioData", Namespace="http://schemas.datacontract.org/2004/07/WcfService.DataContract.DataContract")]
    [System.SerializableAttribute()]
    public partial class UsuarioData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference55.ServiceUsuario")]
    public interface ServiceUsuario {
        
        // CODEGEN: Generating message contract since the wrapper name (UsuarioRequest) of message UsuarioRequest does not match the default value (GetUsuario)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceUsuario/GetUsuario", ReplyAction="http://tempuri.org/ServiceUsuario/GetUsuarioResponse")]
        TesteServico.ServiceReference55.UsuarioResponse GetUsuario(TesteServico.ServiceReference55.UsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsuarioRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TesteServico.ServiceReference55.UsuarioData UsuarioData;
        
        public UsuarioRequest() {
        }
        
        public UsuarioRequest(TesteServico.ServiceReference55.UsuarioData UsuarioData) {
            this.UsuarioData = UsuarioData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TesteServico.ServiceReference55.UsuarioData UsuarioData;
        
        public UsuarioResponse() {
        }
        
        public UsuarioResponse(TesteServico.ServiceReference55.UsuarioData UsuarioData) {
            this.UsuarioData = UsuarioData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceUsuarioChannel : TesteServico.ServiceReference55.ServiceUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUsuarioClient : System.ServiceModel.ClientBase<TesteServico.ServiceReference55.ServiceUsuario>, TesteServico.ServiceReference55.ServiceUsuario {
        
        public ServiceUsuarioClient() {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteServico.ServiceReference55.UsuarioResponse TesteServico.ServiceReference55.ServiceUsuario.GetUsuario(TesteServico.ServiceReference55.UsuarioRequest request) {
            return base.Channel.GetUsuario(request);
        }
        
        public void GetUsuario(ref TesteServico.ServiceReference55.UsuarioData UsuarioData) {
            TesteServico.ServiceReference55.UsuarioRequest inValue = new TesteServico.ServiceReference55.UsuarioRequest();
            inValue.UsuarioData = UsuarioData;
            TesteServico.ServiceReference55.UsuarioResponse retVal = ((TesteServico.ServiceReference55.ServiceUsuario)(this)).GetUsuario(inValue);
            UsuarioData = retVal.UsuarioData;
        }
    }
}
